### ISSUE TITLE
Use pre releases to allow community find bug or patch its packages. 

### ISSUE THREAD

**Issue by Czaki** [python/typing_extensions#185]
The `typing-extension` package is widely used in many projects. It happens that sometimes some package does to strong assumptions (https://github.com/pydantic/pydantic/issues/5821). 

It would be nice if `typing_extension` could create a pre (rc) release and give a few days (for example week) for the community to test it. (example of a project that partially uses this approach is, for example, numpy https://pypi.org/project/numpy/#history)

**Comment by hauntsaninja** [comment]
Thanks for the suggestion!

I definitely agree that typing_extensions is widely used enough that we should try to take steps to ensure people don't break (especially since widespread pinning of typing_extensions can really hurt the adoption of newer type system features)

That said, I'm not sure how much people actually test pre-releases, so I'm a little wary of how much this would actually help. Maybe someone from pydantic can chime in on whether they'd commit to testing prereleases?

We have some other levers here, e.g. we could consider a policy of yanking releases that cause some amount of breakage and waiting a set amount of time before re-releasing. For the specific pydantic issue, it could be worth documenting Jelle's suggestion here: https://github.com/pydantic/pydantic/issues/5821#issuecomment-1559751780 / completing https://github.com/python/typing_extensions/issues/50 could make this mildly easier.

**Comment by JelleZijlstra** [comment]
Another approach could be to run the test suite of some projects that rely heavily on runtime introspection (e.g., pydantic, typing-inspect, pyanalyze) in our CI.

**Comment by mapadofu** [comment]
I assume this is in relation to the way that 4.6.0 breaks some other packages (I saw it with geojson-pydantic/pydantic).

Is the behavior of 4.6.0 the desired behaviour that these other packages need to conform to or is the plan to regain backward compatability?

**Comment by JelleZijlstra** [comment]
The 4.6.0 changes are desired behavior. (Indeed, Pydantic apparently asked for them in the first place.)

With runtime introspection of types, almost any change can break some user. I think we'll put some suggestions for writing robust type-introspection code in the docs..

**Comment by Czaki** [comment]
I dont know how many projects has pre-release test suite. In [napari](https://github.com/napari/napari) we have it and it happens to use to report problem to upstream packages. 

Adoption of pre-release by typing extension may help to propagate pre-release CI jobs in multiple projects.

**Comment by adriangb** [comment]
I'd like to say that Pydantic does a lot of gnarly stuff internally and this issue was mainly caused by us not handling things well enough and is not really typing-extensions responsibility. We should be doing something like what [Jelle suggested](https://github.com/pydantic/pydantic/issues/5821#issuecomment-1559751780) (which Shantu also pointed out above).

Pydantic depends heavily enough on typing-extensions that we should probably be testing against `main` in our CI, which achieves most of what pre-releases do without the burden on the maintainers here.

**Comment by adriangb** [comment]
> Then for long time you should also do this on 1.10.X-fixes branch.
I'm not saying we will, but I agree with you that we should.

> I do not meet projects that run regular tests against the latest release
I agree I haven't seen this, but it also often happens that the bug is still present in HEAD unless it got accidentally patched. But the pre-releases also don't solve this, and that's beyond the scope of this issue.

**Comment by grochmal** [comment]
pydantic is gnarly alright, yet other libraries also depend on similar hacky code.  Mostly due to how the Literal type was evolving during python 3.8.

I have reported [an issue on typed-argument-parser](https://github.com/swansonk14/typed-argument-parser/issues/106) which also uses some hacky code to identify the Literal type.  The typed-argument-parser issue with typing-extensions==4.6.0 is quite similar to the pydantic but not exactly the same issue.

**Comment by JelleZijlstra** [comment]
I opened #189 with some advice for users who rely on runtime introspection of types.

**Comment by AlexWaygood** [comment]
Yes, it is true that pydantic wasn't the only package broken unexpectedly broken here. As well as `typed-argument-parser`, `typing_inspect` also made the same incorrect assumption: https://github.com/ilevkivskyi/typing_inspect/issues/100. So, while this might not have been our "fault", I do think it's in everybody's benefit if we try to figure out how to make this situation less likely in the future.

I'm not sure pre-releases would be very helpful; as @hauntsaninja says, I'm not convinced that very many people test with pre-releases. I like @JelleZijlstra's idea of running the tests for pydantic, and maybe some other projects as well, over at typing_extensions. (We wouldn't necessarily have to do it on every PR or push -- maybe we could have a nightly cron job?)

In terms of making it easier for other projects to follow "introspection best practices": the docs @JelleZijlstra proposes in #189 look great. I also wonder if we could maybe provide an introspection helper like @JelleZijlstra's [suggestion here](https://github.com/pydantic/pydantic/issues/5821#issuecomment-1559751780) ourselves, as part of the typing_extensions API? It seems like lots of projects have a need to do introspection of typing constructs at runtime, and it's quite easy to get it wrong.

**Comment by rsokl** [comment]
FWIW [hydra-zen's CI](https://github.com/mit-ll-responsible-ai/hydra-zen) runs against release candidates and would have caught https://github.com/python/typing_extensions/issues/181 . It also would have been able to warn [beartype that its support for typing_extensions.Protocol was going to break](https://github.com/beartype/beartype/issues/241) with the release of 4.6.0 .

**Comment by ilevkivskyi** [comment]
@AlexWaygood if you will at some point add some daily tests for dependent packages, I would like to opt-in `typing_inspect`, it relies heavily on various `typing_extensions` internals (running against rc/dev will not help much since there are only a handful commits per year).

**Comment by Czaki** [comment]
@ilevkivskyi In napari we have cron job for pre release tests. Maybe it could be also a good solution for you?

**Comment by ilevkivskyi** [comment]
Hm, yeah, this is an interesting idea.

**Comment by AlexWaygood** [comment]
> @AlexWaygood if you will at some point add some daily tests for dependent packages, I would like to opt-in `typing_inspect`

(That sounds good to me, but I'm not actually a `typing_extensions` maintainer right now, just a regular contributor, so it's not really my call :)

**Comment by JelleZijlstra** [comment]
I think doing release candidates is a good idea. I opened #197 to formalize such a policy.

I also opened issue #198 to track the idea floated above of running third-party projects' test suites against typing-extensions regularly.
