### ISSUE TITLE
Unreadable help() with Annotated[str, Doc(...)]

### ISSUE THREAD

**Issue by saper** [python/typing_extensions#300]
![fastapi-ugly-help](https://github.com/python/typing_extensions/assets/248374/a29d9682-508e-4577-abe6-e2da04668838)

The above is how `pydoc3 fastapi.FastAPI` looks in my terminal. Do you have any idea how this could become more readable?

**Comment by JelleZijlstra** [comment]
I think there's a couple of things we could do in CPython's implementation of help() if PEP 727 is accepted (which at this point, doesn't look terribly likely):

- Run `inspect.cleandoc` on the Doc strings, to get rid of the excessive whitespace and newlines
- Format the signature so that every parameter ends up on its own line
- Parse out Doc() instances and format them specially

However, I don't think there's much we can do in typing-extensions.

cc @tiangolo

**Comment by JelleZijlstra** [comment]
I feel my second suggestion would be useful regardless of PEP 727, so I filed a CPython feature request for it: python/cpython#112139.

**Comment by AlexWaygood** [comment]
Agreed that there's nothing here that's actionable for `typing_extensions`. Let's continue discussion on the CPython issue; improving the output of `help()` for functions with long signatures sounds like a great idea!
