### ISSUE TITLE
Hints for using typing_extensions with mypy

### ISSUE THREAD

**Issue by tgamblin** [python/typing_extensions#316]
Is there a rough set of recommendations for how to configure `mypy` with different `typing_extension` versions?

For example, it looks like the last version of `typing_extensions` to support Python 3.6 was 4.1.1.  If I use typing_extensions 4.1.1 with python 3.6, should I set `mypy`'s `python_version` to 3.8?  3.9? Something else?

**Comment by JelleZijlstra** [comment]
I'm not sure there's much to be said from the typing-extensions side. If you want mypy to check Python 3.6, you should set mypy's python_version to 3.6, and pick an appropriate version of typing-extensions.

**Comment by hauntsaninja** [comment]
+1 to everything Jelle said.

Additionally, note that because typing-extensions is highly special cased, type checkers are not typically aware of differences between versions of typing-extensions and usually pretend that typing-extensions works the way the latest release of typing-extensions did at the time that the version of your type checker was released.

This typically isn't a big deal. If your type checker is much newer than your typing-extensions you might get a false negative which will usually result in an import time error. If your typing-extensions is much newer than your type checker you might get a somewhat false positive, but new symbols in typing-extensions often require special case support in type checkers anyway so it's arguable how false such false positives would be.

**Comment by hauntsaninja** [comment]
> Isn’t setting mypy’s Python version to 3.6 going to prevent me from using the new features in typing extensions?

No

**Comment by tgamblin** [comment]
Thanks! My example was somewhat contrived. We support running on Python 3.6-3.12, but we’re currently setting `--python-version` to 3.7, and haven’t found that mypy admits any annotations that are source-incompatible with 3.6 (I’m not familiar enough to say if there are any).

Most devs are on newer Python versions (3.11, 3.12) and we don’t require that mypy itself be run from Python 3.6.
