### ISSUE TITLE
Different results in Python 3.12.1 vs Python 3.12.2

### ISSUE THREAD

**Issue by tfeldmann** [python/typing_extensions#335]
Small reproducer:

```python
from dataclasses import dataclass

from typing_extensions import Protocol, runtime_checkable


@runtime_checkable  # removing this decorator fixes the bug.
class HasConfig(Protocol):
    pass

@runtime_checkable
class Action(HasConfig, Protocol):
    pass

@dataclass
class Delete:
    pass

delete = Delete()
print(isinstance(delete, Action))
```

This prints `False` in 3.12.2, `True` in 3.12.1. Changing the import to `from typing import Protocol, runtime_checkable` also makes this bug disappear.

**Comment by AlexWaygood** [comment]
This is because Python 3.12.2 changed the implementation of `@runtime_checkable` so that it now adds an attribute to the class it decorates. We've actually already fixed this bug on the `typing_extensions` main branch (in https://github.com/python/typing_extensions/commit/004b893ddce2a5743d9a4de3a97ef5c48882d384), but the fix hasn't been released yet.

@JelleZijlstra -- thoughts on possibly reconsidering https://github.com/python/typing_extensions/pull/324#issuecomment-1944109810? I think it might be worth cutting a patch release for this :/ Sorry for the bother :(

**Comment by JelleZijlstra** [comment]
I feel the changes are too big for a bugfix release. I merged the PEP 742 implementation and hopefully we can also get PEP 728 implemented in the next few days, then make a release on Sunday (#337).

**Comment by AlexWaygood** [comment]
typing_extensions 4.10.0 has now been released, which should hopefully fix the issue! Let us know if you're still having problems @tfeldmann
